plugins {
    id 'com.android.application'
}

android {
    namespace 'com.workbuddy.roomchat'
    compileSdk 34

    defaultConfig {
        applicationId "com.workbuddy.roomchat"
        minSdk 24
        targetSdk 34
        versionCode 15
        versionName "1.1.4"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
